### Register new user
POST {{url}}/auth/register
Content-Type: application/json

{
  "email": "mateo@admin.com",
  "password": "password123"
}

### Login
POST {{url}}/auth/login
Content-Type: application/json

{
  "email": "mateo@admin.com",
  "password": "password123"
}
> {%client.global.set("access_token", response.body.access_token)%}

### Example Protected Route (use token from login response)
GET {{url}}/some-protected-route
Authorization: Bearer {{access_token}} 