### Get all clients
GET {{url}}/clients?q=pepe
Authorization: Bearer {{access_token}}

### Get a client by ID
GET {{url}}/clients/1
Authorization: Bearer {{access_token}}

### Create a new client
POST {{url}}/clients
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "name": "Fulanito",
  "lastName": "Prueba",
  "dni": "41148747",
  "phone": "555-1234",
  "address": "123 Main St"
}

### Update a client by ID
PATCH {{url}}/clients/{{id}}
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "name": "Jane",
  "lastName": "Smith",
  "dni": "87654321",
  "phone": "555-5678",
  "address": "456 Elm St",
  "role": "CLIENT",
}
