### Get all employees
GET {{url}}/employees HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{access_token}}

### Get all employees without routes
GET {{url}}/employees?withoutRoutes=true HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{access_token}}

### Get employee by ID
GET {{url}}/employees/6 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{access_token}}

### Create new employee
POST {{url}}/employees HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "name": "Manuel",
  "lastName": "Gomez",
  "dni": "23563432",
  "phone": "555-1234",
  "address": "123 Main St",
  "role": "EMPLOYEE"
}

### Update employee
PATCH {{url}}/employees/6 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "order": {
    "id": 4
  },
  "routes": [
    {
      "lat": -31.41400,
      "lng": -64.16500
    }
  ]
}

### Delete employee
DELETE {{url}}/employees/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{access_token}}
