### Get all orders
GET {{url}}/orders
Content-Type: application/json
Authorization: Bearer {{access_token}}

### Get all orders for client
GET {{url}}/orders?clientId=1&q=4
Content-Type: application/json
Authorization: Bearer {{access_token}}

### Get order by ID
GET {{url}}/orders/2
Content-Type: application/json
Authorization: Bearer {{access_token}}

### Get sales history
GET {{url}}/orders/sales?startDate=2025-04-06&endDate=2025-05-08
Content-Type: application/json
Authorization: Bearer {{access_token}}

### Create new order
POST {{url}}/orders
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "client": {
    "id": 1
  },
  "employeeAssigned": {
    "id": 4
  },
  "address": "123 Main St, City, Country",
  "statusDelivery": "pending",
  "statusPayment": "pending",
  "items": [
    {
      "quantity": 2,
      "product": {
        "id": 1
      }
    }
  ]
}

### Update order
PUT {{url}}/orders/1
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "statusDelivery": "delivered",
  "items": [
    {
      "quantity": 5,
      "product": {
        "id": 1
      }
    },
    {
      "quantity": 1,
      "product": {
        "id": 3
      }
    }
  ]
}

### Delete order
DELETE {{url}}/orders/1
Content-Type: application/json
Authorization: Bearer {{access_token}}
