### Get all orders
GET {{url}}/orders
Content-Type: application/json

### Get all orders for client
GET {{url}}/orders?clientId=1
Content-Type: application/json

### Get order by ID
GET {{url}}/orders/4
Content-Type: application/json

### Get sales history
GET {{url}}/orders/sales?startDate=2024-01-01&endDate=2026-01-31
Content-Type: application/json

### Create new order
POST {{url}}/orders
Content-Type: application/json

{
  "client": {
    "id": 1
  },
  "employeeAssigned": {
    "id": 4
  },
  "address": "123 Main St, City, Country",
  "statusDelivery": "pending",
  "statusPayment": "pending",
  "items": [
    {
      "quantity": 2,
      "product": {
        "id": 1
      }
    }
  ]
}

### Update order
PUT {{url}}/orders/1
Content-Type: application/json

{
  "statusDelivery": "delivered",
  "items": [
    {
      "quantity": 5,
      "product": {
        "id": 1
      }
    },
    {
      "quantity": 1,
      "product": {
        "id": 3
      }
    }
  ]
}

### Delete order
DELETE {{url}}/orders/1
Content-Type: application/json
