### Get all products
GET {{url}}/products
Authorization: Bearer {{access_token}}

### Get a product by ID
GET {{url}}/products/{{id}}
Authorization: Bearer {{access_token}}

### Create a new product
POST {{url}}/products
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "name": "Jabon liquido",
  "price": 100,
  "description": "Jabon liquido para lavar las manos",
  "category": "Jabon",
  "lot": {
    "unitOfMeasure": "un",
    "quantity": 10
  }
}

### Update a product by ID
PATCH {{url}}/products/{{id}}
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "name": "Updated Product",
  "price": 150
}
